// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfxVEcjhdBKKOQPbPt_HYK1WEHmZqCmS4',
    appId: '1:671068093083:web:3c0a6e8da81a1ee6c1643e',
    messagingSenderId: '671068093083',
    projectId: 'crud-all',
    authDomain: 'crud-all.firebaseapp.com',
    storageBucket: 'crud-all.appspot.com',
    measurementId: 'G-HQ9M9Z29NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB87NwwfoFe64im-er6O-aJPKHx8AK0AMU',
    appId: '1:671068093083:android:ba93ad4a6d1fc735c1643e',
    messagingSenderId: '671068093083',
    projectId: 'crud-all',
    storageBucket: 'crud-all.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2uMUbjLu8Lndcd9-QTGJczfjKckBvvfY',
    appId: '1:671068093083:ios:a6fd2a89d1d798dec1643e',
    messagingSenderId: '671068093083',
    projectId: 'crud-all',
    storageBucket: 'crud-all.appspot.com',
    iosClientId: '671068093083-nijh0cqfvp3dl2oi02k6b3to0iu1mh16.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudAll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2uMUbjLu8Lndcd9-QTGJczfjKckBvvfY',
    appId: '1:671068093083:ios:a6fd2a89d1d798dec1643e',
    messagingSenderId: '671068093083',
    projectId: 'crud-all',
    storageBucket: 'crud-all.appspot.com',
    iosClientId: '671068093083-nijh0cqfvp3dl2oi02k6b3to0iu1mh16.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudAll',
  );
}
